apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport-service
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30007  # Optionally specify a node port in the range 30000-32767, or leave this out to have Kubernetes assign one automatically.

